# permissions for end users to edit coreuis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: microservice-operator
    app.kubernetes.io/managed-by: kustomize
  name: coreui-editor-role
rules:
- apiGroups:
  - microservice.alveotech.com
  resources:
  - coreuis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microservice.alveotech.com
  resources:
  - coreuis/status
  verbs:
  - get
