---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - microservice.alveotech.com
  resources:
  - coreuis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - microservice.alveotech.com
  resources:
  - coreuis/finalizers
  verbs:
  - update
- apiGroups:
  - microservice.alveotech.com
  resources:
  - coreuis/status
  verbs:
  - get
  - patch
  - update
