apiVersion: example.example.com/v1
kind: Microservice
metadata:
  labels:
    app.kubernetes.io/name: microservice-operator
    app.kubernetes.io/managed-by: kustomize
  name: microservice-sample
spec:
  # TODO(user): Add fields here
